In [2]:
#Dependencies 
import os
import csv

import pandas as pd

In [3]:
# Path to collect data from the Resources folder
foodAccessData_csv = os.path.join('Resources', 'AZ Food Access Research Atlas.csv')

In [4]:
# Read in the CSV file
with open(foodAccessData_csv) as csvfile:

    # Split the data on commas
    csvreader = csv.reader(csvfile, delimiter=',')

In [5]:
# Use Pandas to read data
food_access_df = pd.read_csv(foodAccessData_csv)
food_access_df.head(100)

,CensusTract,State,County,Urban,POP2010,OHU2010,GroupQuartersFlag,NUMGQTRS,PCTGQTRS,LILATracts_1And10,...,TractSeniors,TractWhite,TractBlack,TractAsian,TractNHOPI,TractAIAN,TractOMultir,TractHispanic,TractHUNV,TractSNAP
0,4001942600,Arizona,Apache,0,1578,447,0,0,0.000000,1,...,180,13,1,0,0,1550,14,35,56,130
1,4001942700,Arizona,Apache,0,5628,1700,0,0,0.000000,1,...,644,96,2,12,1,5444,73,97,164,290
2,4001944000,Arizona,Apache,0,6043,1821,0,3,0.000496,1,...,569,244,12,57,4,5581,145,136,116,289
3,4001944100,Arizona,Apache,0,5870,1632,0,204,0.034753,1,...,482,65,3,1,0,5725,76,77,267,464
4,4001944201,Arizona,Apache,0,4010,1146,0,56,0.013965,0,...,302,244,15,11,0,3662,78,110,107,339
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,4009961202,Arizona,Graham,0,3609,1248,0,3,0.000831,0,...,472,3155,8,29,2,30,385,964,42,142
96,4009961300,Arizona,Graham,1,3409,1271,0,148,0.043414,0,...,571,2695,44,26,1,81,562,1539,100,325
97,4009961400,Arizona,Graham,1,4947,1696,0,96,0.019406,0,...,713,4072,62,56,4,54,699,2191,143,335
98,4009961500,Arizona,Graham,0,4449,1509,0,32,0.007193,0,...,532,3782,16,10,3,61,577,1546,31,373
99,4009961600,Arizona,Graham,0,3161,394,1,2203,0.696931,0,...,168,2277,271,42,21,173,377,1340,3,69

Section below is example code I can edit & use to narrow my df to Maricopa county only.

In [6]:
# Create a new DataFrame that looks into a specific county
maricopa_food_access_df = food_access_df.loc[food_access_df["County"] == "Maricopa"]
maricopa_food_access_df

,CensusTract,State,County,Urban,POP2010,OHU2010,GroupQuartersFlag,NUMGQTRS,PCTGQTRS,LILATracts_1And10,...,TractSeniors,TractWhite,TractBlack,TractAsian,TractNHOPI,TractAIAN,TractOMultir,TractHispanic,TractHUNV,TractSNAP
113,4013010101,Arizona,Maricopa,0,5073,2246,0,0,0.000000,0,...,1645,4869,44,61,7,12,80,161,42,0
114,4013010102,Arizona,Maricopa,1,4640,2041,0,0,0.000000,0,...,1240,4367,21,108,5,6,133,169,73,14
115,4013030401,Arizona,Maricopa,1,4283,2008,0,47,0.010974,0,...,1431,4100,30,65,0,11,77,111,58,21
116,4013030402,Arizona,Maricopa,1,3895,1706,0,0,0.000000,0,...,792,3627,27,27,3,18,193,320,0,19
117,4013040502,Arizona,Maricopa,1,4861,2188,0,169,0.034766,1,...,1340,4343,12,24,1,85,396,759,195,258
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1024,4013980100,Arizona,Maricopa,0,0,0,0,0,0.000000,0,...,0,0,0,0,0,0,0,0,0,0
1025,4013980400,Arizona,Maricopa,1,15,5,0,8,0.533333,1,...,0,5,0,8,0,0,2,2,0,0
1026,4013980500,Arizona,Maricopa,0,0,0,0,0,0.000000,0,...,0,0,0,0,0,0,0,0,0,0
1027,4013980600,Arizona,Maricopa,0,0,0,0,0,0.000000,0,...,0,0,0,0,0,0,0,0,0,0
1028,4013980700,Arizona,Maricopa,0,4,2,0,0,0.000000,0,...,2,4,0,0,0,0,0,0,0,0

In [7]:
# Dependencies
# Python SQL toolkit and Object Relational Mapper
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
# Imports the method used for connecting to DBs
from sqlalchemy import create_engine

In [8]:
# Imports the methods needed to abstract classes into tables
from sqlalchemy.ext.declarative import declarative_base
Base = declarative_base()

In [9]:
# Allow us to declare column types
from sqlalchemy import Column, Integer, String, Float

In [10]:
#pgAdmin password
from config import pswrd, port, sql

In [11]:
# Create engine using the `FoodForAll.postgres` database file
engine = create_engine(f'postgresql://postgres:{pswrd}@localhost:{port}/{sql}')

In [12]:
# # Create Classes# Define our desert_data table
# class desert_data(Base):
#     __tablename__ = 'foodAccess'
#     id = Column(Integer, primary_key=True)
#     state = Column(String)
#     County = Column(String)
#     Urban = Column (Integer)
#     POP2010 = Column(Integer)
#     OHU2010 = Column(Integer)
#     GroupQuartersFlag = Column(Integer)
#     NUMGQTRS = Column(Integer)
#     PCTGQTRS = Column(Float)
#     LILATracts_1And10 = Column(Integer)
#     LILATracts_halfAnd10 = Column(Integer)
#     LILATracts_1And20 = Column(Integer)
#     LILATracts_Vehicle = Column(Integer)
#     HUNVFlag = Column(Integer)
#     LowIncomeTracts = Column(Integer)
#     PovertyRate = Column(Integer)
#     MedianFamilyIncome = Column(Integer)
#     LowIncomeTracts = Column(Integer)
#     LA1and10 = Column(Integer)
#     LAhalfand10 = Column(Integer)
#     LA1and20 = Column(Integer)
#     LATracts_half = Column(Integer)
#     LATracts1 = Column(Integer)
#     LATracts10 = Column(Integer)
#     LATracts20 = Column(Integer)
#     LATractsVehicle_20 = Column(Integer)
#     LAPOP1_10 = Column(Float)
#     LAPOP05_10 = Column(Float)
#     LAPOP1_20 = Column(Float)
#     LALOWI1_10 = Column(Float)
#     LALOWI05_10 = Column(Float)
#     LALOWI1_20 = Column(Float)
#     lapophalf = Column(Float)
#     lapophalfshare = Column(Float)
#     lalowihalf = Column(Float)
#     lalowihalfshare = Column(Float)
#     lakidshalf = Column(Float)
#     lakidshalfshare = Column(Float)
#     laseniorshalf = Column(Float)
#     laseniorshalfshare = Column(Float)
#     lawhitehalf = Column(Float)
#     lawhitehalfshare = Column(Float)
#     lablackhalf = Column(Float)
#     lablackhalfshare = Column(Float)
#     laasianhalf = Column(Float)
#     laasianhalfshare = Column(Float)
#     lanhopihalf = Column(Float)
#     lanhopihalfshare = Column(Float)
#     laaianhalf = Column(Float)
#     laaianhalfshare = Column(Float)
#     laomultirhalf = Column(Float)
#     laomultirhalfshare = Column(Float)
#     lahisphalf = Column(Float)
#     lahisphalfshare = Column(Float)
#     lahunvhalf = Column(Float)
#     lahunvhalfshare = Column(Float)
#     lasnaphalf = Column(Float)
#     lasnaphalfshare = Column(Float)
#     lapop1 = Column(Float)
#     lapop1share = Column(Float)  
#     lalowi1 = Column(Float)
#     lalowi1share = Column(Float)
#     lakids1 = Column(Float)
#     lakids1share = Column(Float)
#     laseniors1 = Column(Float)
#     laseniors1share = Column(Float)
#     lawhite1 = Column(Float)
#     lawhite1share = Column(Float)
#     lablack1 = Column(Float)
#     lablack1share = Column(Float)
#     lalaasian1 = Column(Float)
#     lalaasian1share = Column(Float)
#     lanhopi1 = Column(Float)
#     lanhopi1share = Column(Float)
#     laaian1 = Column(Float)
#     lablack1share = Column(Float)
#     laaian1share = Column(Float)
#     laomultir1 = Column(Float)
#     laomultir1share = Column(Float)
#     lahisp1 = Column(Float)
#     lahisp1share = Column(Float)
#     lahunv1 = Column(Float)
#     lahunv1share = Column(Float)
#     lalasnap1 = Column(Float)
#     lalasnap1share = Column(Float)
#     lapop10 = Column(Float)
#     lapop10share = Column(Float)
#     lalowi10 = Column(Float)
#     lalowi10share = Column(Float)
#     lakids10 = Column(Float)
#     lakids10share = Column(Float)
#     laseniors10 = Column(Float)
#     laseniors10share = Column(Float)
#     lawhite10 = Column(Float)
#     lawhite10share = Column(Float)
#     lablack10 = Column(Float)
#     lablack10share = Column(Float)
#     laasian10 = Column(Float)
#     laasian10share = Column(Float)
#     lanhopi10 = Column(Float)
#     lanhopi10share = Column(Float)
#     laaian10 = Column(Float)
#     laaian10share = Column(Float)
#     laomultir10 = Column(Float)
#     laomultir10share = Column(Float)
#     lahisp10 = Column(Float)
#     lahisp10share = Column(Float)
#     LowIncomeTracts = Column(Float)
#     lahunv10share = Column(Float)
#     lasnap10 = Column(Float)
#     lasnap10share = Column(Float)
#     lapop20 = Column(Float)
#     lapop20share = Column(Float)
#     lalowi20 = Column(Float)
#     lalowi20share = Column(Float)
#     lakids20 = Column(Float)
#     lakids20share = Column(Float)
#     laseniors20 = Column(Float)
#     laseniors20share = Column(Float)
#     lawhite20 = Column(Float)
#     lawhite20share = Column(Float)
#     lablack20 = Column(Float)
#     lablack20share = Column(Float)
#     laasian20 = Column(Float)
#     laasian20share = Column(Float)
#     lanhopi20 = Column(Float)
#     lanhopi20share = Column(Float)
#     laaian20 = Column(Float)
#     laaian20share = Column(Float)
#     laomultir20 = Column(Float)
#     laomultir20share = Column(Float)
#     lahisp20 = Column(Float)
#     lahisp20share = Column(Float)
#     lahunv20 = Column(Float)
#     lahunv20share = Column(Float)
#     lasnap20 = Column(Float)
#     lasnap20share = Column(Float)
#     TractLOWI = Column(Float)
#     TractKids = Column(Float)
#     TractSeniors = Column(Float)
#     TractWhite = Column(Float)
#     TractBlack = Column(Float)
#     TractAsian = Column(Float)
#     TractNHOPI = Column(Float)
#     TractAIAN = Column(Float)
#     TractOMultir = Column(Float)
#     TractHispanic = Column(Float)
#     TractHUNV = Column(Float)
#     TractSNAP = Column(Float)

In [13]:
#make sure this table doesn't exist already in the DB
maricopa_food_access_df.to_sql('desert_data', engine, if_exists='replace')

In [12]:
# Declare a Base using `automap_base()`
Base = automap_base()

In [13]:
# Use the Base class to reflect the database tables
Base.prepare(engine, reflect=True)

In [14]:
# Print all of the classes mapped to the Base
Base.classes.keys()

[]

In [ ]:
# Create the inspector and connect it to the engine
inspector = inspect(engine)

In [ ]:
# Collect the names of tables within the database
inspector.get_table_names()

In [16]:
# Assign the desert_data class to a variable called `desert_data`
#desert_data = Base.classes.desert_data

In [ ]:
# Create a session
#session = Session(engine)

In [ ]:
# Use the session to query desert_data table and display the first 5 locations
# for row in session.query(desert_data, desert_data.location).limit(5).all():
#    print(row[1])