In [53]:
#Dependencies 
import os
import csv

import pandas as pd

In [54]:
# Path to collect data from the Resources folder
foodAccessData_csv = os.path.join('Resources', 'AZ Food Access Research Atlas.csv')

In [55]:
# Read in the CSV file
with open(foodAccessData_csv) as csvfile:

    # Split the data on commas
    csvreader = csv.reader(csvfile, delimiter=',')

In [56]:
# Use Pandas to read data
food_access_df = pd.read_csv(foodAccessData_csv)
food_access_df.head(100)

,CensusTract,State,County,Urban,POP2010,OHU2010,GroupQuartersFlag,NUMGQTRS,PCTGQTRS,LILATracts_1And10,...,TractSeniors,TractWhite,TractBlack,TractAsian,TractNHOPI,TractAIAN,TractOMultir,TractHispanic,TractHUNV,TractSNAP
0,4001942600,Arizona,Apache,0,1578,447,0,0,0.000000,1,...,180,13,1,0,0,1550,14,35,56,130
1,4001942700,Arizona,Apache,0,5628,1700,0,0,0.000000,1,...,644,96,2,12,1,5444,73,97,164,290
2,4001944000,Arizona,Apache,0,6043,1821,0,3,0.000496,1,...,569,244,12,57,4,5581,145,136,116,289
3,4001944100,Arizona,Apache,0,5870,1632,0,204,0.034753,1,...,482,65,3,1,0,5725,76,77,267,464
4,4001944201,Arizona,Apache,0,4010,1146,0,56,0.013965,0,...,302,244,15,11,0,3662,78,110,107,339
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,4009961202,Arizona,Graham,0,3609,1248,0,3,0.000831,0,...,472,3155,8,29,2,30,385,964,42,142
96,4009961300,Arizona,Graham,1,3409,1271,0,148,0.043414,0,...,571,2695,44,26,1,81,562,1539,100,325
97,4009961400,Arizona,Graham,1,4947,1696,0,96,0.019406,0,...,713,4072,62,56,4,54,699,2191,143,335
98,4009961500,Arizona,Graham,0,4449,1509,0,32,0.007193,0,...,532,3782,16,10,3,61,577,1546,31,373
99,4009961600,Arizona,Graham,0,3161,394,1,2203,0.696931,0,...,168,2277,271,42,21,173,377,1340,3,69

Section below is example code I can edit & use to narrow my df to Maricopa county only.

In [57]:
# Create a new DataFrame that looks into a specific county
maricopa_food_access_df = food_access_df.loc[food_access_df["County"] == "Maricopa"]
maricopa_food_access_df

,CensusTract,State,County,Urban,POP2010,OHU2010,GroupQuartersFlag,NUMGQTRS,PCTGQTRS,LILATracts_1And10,...,TractSeniors,TractWhite,TractBlack,TractAsian,TractNHOPI,TractAIAN,TractOMultir,TractHispanic,TractHUNV,TractSNAP
113,4013010101,Arizona,Maricopa,0,5073,2246,0,0,0.000000,0,...,1645,4869,44,61,7,12,80,161,42,0
114,4013010102,Arizona,Maricopa,1,4640,2041,0,0,0.000000,0,...,1240,4367,21,108,5,6,133,169,73,14
115,4013030401,Arizona,Maricopa,1,4283,2008,0,47,0.010974,0,...,1431,4100,30,65,0,11,77,111,58,21
116,4013030402,Arizona,Maricopa,1,3895,1706,0,0,0.000000,0,...,792,3627,27,27,3,18,193,320,0,19
117,4013040502,Arizona,Maricopa,1,4861,2188,0,169,0.034766,1,...,1340,4343,12,24,1,85,396,759,195,258
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1024,4013980100,Arizona,Maricopa,0,0,0,0,0,0.000000,0,...,0,0,0,0,0,0,0,0,0,0
1025,4013980400,Arizona,Maricopa,1,15,5,0,8,0.533333,1,...,0,5,0,8,0,0,2,2,0,0
1026,4013980500,Arizona,Maricopa,0,0,0,0,0,0.000000,0,...,0,0,0,0,0,0,0,0,0,0
1027,4013980600,Arizona,Maricopa,0,0,0,0,0,0.000000,0,...,0,0,0,0,0,0,0,0,0,0
1028,4013980700,Arizona,Maricopa,0,4,2,0,0,0.000000,0,...,2,4,0,0,0,0,0,0,0,0

In [58]:
# Dependencies
# Python SQL toolkit and Object Relational Mapper
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
# Imports the method used for connecting to DBs
from sqlalchemy import create_engine

In [59]:
# Imports the methods needed to abstract classes into tables
from sqlalchemy.ext.declarative import declarative_base
Base = declarative_base()

In [60]:
# Allow us to declare column types
from sqlalchemy import Column, Integer, String, Float

In [61]:
#pgAdmin password, postgress port, database name hidden in config file
from config import pswrd, port, sql

In [62]:
# Create engine using the `FoodForAll.postgres` database file
engine = create_engine(f'postgresql://postgres:{pswrd}@localhost:{port}/{sql}')

In [63]:
#make sure this table doesn't exist already in the DB
maricopa_food_access_df.to_sql('desert_data', engine, if_exists='replace')

In [32]:
# Path to collect data from the Resources folder
snap_csv = os.path.join('Resources', 'snap.csv')

In [33]:
# Read in the CSV file
with open(snap_csv) as csvfile:

    # Split the data on commas
    csvreader = csv.reader(csvfile, delimiter=',')

In [34]:
# Use Pandas to read data
snap_df = pd.read_csv(snap_csv)
snap_df.head(100)

,Unnamed: 0,Store_Name,Address,Address_Line__2,City,State,Zip5,Zip4,County,Longitude,Latitude,ObjectId,FIPS,Census Tract
0,42,Kwik Corner 5059,5059 W Olive Ave,NaN,Glendale,AZ,85302,3524.0,MARICOPA,-112.16846,33.566959,43,40130923092004,4013092309
1,120,Grand Ave Produce,8990 W Windsor Dr,NaN,Peoria,AZ,85381,6152.0,MARICOPA,-112.25265,33.600914,121,40130715171009,4013071517
2,524,Big Az Market 2 2,51348 W Highway 60,NaN,Aguila,AZ,85320,199.0,MARICOPA,-113.17298,33.943394,525,40130405151290,4013040515
3,549,Pride Food Mart,1734 E Apache Blvd,NaN,Tempe,AZ,85281,5958.0,MARICOPA,-111.90952,33.414875,550,40133191032005,4013319103
4,627,Caribbean Oasis,2958 N 16th St,NaN,Phoenix,AZ,85016,7606.0,MARICOPA,-112.04771,33.481934,628,40131106004015,4013110600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,8957,Speedway 3004,JUNCTION HWY 160 & 163,NaN,KAYENTA,AZ,86033,NaN,NAVAJO,-110.41938,36.660816,8958,40179424001666,4017942400
96,9113,Circle K 2723410,2275 S Buffalo Soldier Trl,NaN,Sierra Vista,AZ,85635,6429.0,COCHISE,-110.29019,31.527756,9114,40030018002032,4003001800
97,9210,Corner Store 2741665,10335 E Drexel Rd,NaN,Tucson,AZ,85747,9405.0,PIMA,-110.77200,32.147999,9211,40190040631021,4019004063
98,9337,Family Dollar 8644,4239 W McDowell Rd,Ste 24,Phoenix,AZ,85009,NaN,MARICOPA,-112.14997,33.465942,9338,40131126011001,4013112601
99,9403,Pilot Travel Center 611,6700 W Latham St,NaN,Phoenix,AZ,85043,1400.0,MARICOPA,-112.20573,33.460136,9404,40131125081001,4013112508

In [35]:
# Create a new DataFrame that looks into a specific county
snap_df = snap_df.loc[snap_df["County"] == "Maricopa"]
snap_df

Empty DataFrame
Columns: [Unnamed: 0, Store_Name, Address, Address_Line__2, City, State, Zip5, Zip4, County, Longitude, Latitude, ObjectId, FIPS, Census Tract]
Index: []

In [36]:
# Path to collect data from the Resources folder
bs_csv = os.path.join('Resources', 'bs.csv')

In [37]:
# Read in the CSV file
with open(bs_csv) as csvfile:

    # Split the data on commas
    csvreader = csv.reader(csvfile, delimiter=',')

In [38]:
# Use Pandas to read data
bus_df = pd.read_csv(bs_csv)
bus_df.head(100)

,Unnamed: 0,OBJECTID,StopID,NextRide,Location,Juris,Shelter,Bench,TrashCan,BusBay,...,DateUpdated,Sidewalk,Photo,ATIS_ID,Direction,Long,Lat,Routes,FIPS,Census Tract
0,0,1.0,5182.0,16020.0,MESA DR & MAIN ST,Mesa,1.0,1.0,0.0,No,...,1.541148e+12,NaN,https://farm9.staticflickr.com/8719/1692170720...,5196.0,Southbound,-111.823076,33.414719,120,4.013421e+13,4.013421e+09
1,1,2.0,2982.0,16001.0,MESA DR & MAIN ST,Mesa,1.0,4.0,1.0,Yes,...,1.541148e+12,Yes,https://farm1.staticflickr.com/757/21334866928...,2996.0,Northbound,-111.822766,33.415684,120,4.013422e+13,4.013422e+09
2,2,3.0,4681.0,16016.0,MESA DR & 6TH ST,Mesa,1.0,1.0,1.0,No,...,1.541148e+12,Yes,https://farm8.staticflickr.com/7288/1632759920...,4695.0,Southbound,-111.822934,33.425734,120,4.013421e+13,4.013421e+09
3,3,4.0,4682.0,16017.0,MESA DR & UNIVERSITY DR,Mesa,1.0,1.0,1.0,No,...,1.541148e+12,Yes,https://farm9.staticflickr.com/8622/1630995151...,4696.0,Southbound,-111.823048,33.422048,120,4.013421e+13,4.013421e+09
4,4,5.0,4679.0,16019.0,MESA DR & 1ST ST,Mesa,0.0,1.0,1.0,No,...,1.541148e+12,Yes,https://farm8.staticflickr.com/7292/1587753502...,4693.0,Southbound,-111.823069,33.416883,120,4.013421e+13,4.013421e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,110.0,2895.0,16206.0,GILBERT RD & UNIVERSITY DR,Mesa,1.0,2.0,1.0,Yes,...,1.541148e+12,Yes,https://farm8.staticflickr.com/7445/1649667817...,2909.0,Northbound,-111.787911,33.423403,136,4.013421e+13,4.013421e+09
96,96,111.0,4722.0,16746.0,POWER RD & INGLEWOOD ST,Mesa,0.0,0.0,0.0,No,...,1.541148e+12,Yes,https://farm9.staticflickr.com/8570/1649667242...,4736.0,Southbound,-111.684319,33.447785,184,4.013420e+13,4.013420e+09
97,97,112.0,9110.0,10038.0,S GILBERT RD & E FAIRVIEW ST,Gilbert,1.0,2.0,1.0,No,...,1.541148e+12,Yes,https://farm8.staticflickr.com/7368/1647166616...,11510.0,Northbound,-111.789500,33.295974,136,4.013815e+13,4.013815e+09
98,98,113.0,3032.0,16738.0,POWER RD & UNIVERSITY DR,Mesa,1.0,1.0,1.0,Yes,...,1.541148e+12,Yes,https://farm8.staticflickr.com/7397/1587754009...,3046.0,Northbound,-111.684241,33.423542,184,4.013420e+13,4.013420e+09
99,99,114.0,5220.0,12579.0,POWER RD & SOUTHERN AVE,Mesa,0.0,0.0,0.0,No,...,1.541148e+12,Yes,https://farm8.staticflickr.com/7372/1631140311...,5234.0,Southbound,-111.684945,33.393552,40 | 45 | 61 | 184,4.013423e+13,4.013423e+09

In [49]:
# Create engine using the `FoodForAll.postgres` database file
engine = create_engine(f'postgresql://postgres:{pswrd}@localhost:{port}/{sql}')

In [39]:
# Path to collect data from the Resources folder
lr_csv = os.path.join('Resources', 'lr.csv')

In [40]:
# Read in the CSV file
with open(lr_csv) as csvfile:

    # Split the data on commas
    csvreader = csv.reader(csvfile, delimiter=',')

In [41]:
# Use Pandas to read data
lrail_df = pd.read_csv(lr_csv)
lrail_df.head(100)

,Unnamed: 0,OBJECTID,StationId,StationName,Jurisdiction,StationStatus,POINT_X,POINT_Y,Image,Image2,...,TrashCan,BikeRacks,WaterFountain,Restroom,InfoDisplay,Em_Call,NextRide,Address,FIPS,Census Tract
0,0,1,1,19th Avenue / Dunlap Avenue,Phoenix,In Operation,-112.099389,33.567090,https://farm8.staticflickr.com/7090/2653039729...,https://farm8.staticflickr.com/7641/2703965492...,...,NaN,NaN,NaN,NaN,NaN,NaN,18608,1935 W Dunlap Ave,40131054002012,4013105400
1,1,2,35,Center Street / Main Street,Mesa,In Operation,-111.830660,33.415098,https://farm6.staticflickr.com/5812/2398469262...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,18602,26 East Main Street,40134214001019,4013421400
2,2,3,2,19th Avenue / Northern Avenue,Phoenix,In Operation,-112.099360,33.553190,https://farm8.staticflickr.com/7505/2710105440...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,18607,7832 N 19th Ave,40131054003002,4013105400
3,3,4,3,19th Avenue / Glendale Avenue,Phoenix,In Operation,-112.099329,33.538643,https://farm8.staticflickr.com/7167/2653039369...,https://farm8.staticflickr.com/7377/2686011248...,...,NaN,NaN,NaN,NaN,NaN,NaN,18606,6813 N 19th Ave,40131061003007,4013106100
4,4,5,21,44th Street / Washington,Phoenix,In Operation,-111.987983,33.448170,https://farm6.staticflickr.com/5771/2343906011...,https://farm2.staticflickr.com/1502/2344359052...,...,NaN,NaN,NaN,NaN,NaN,NaN,10018,4203 East Washington Street,40131138011012,4013113801
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,83,87,16,Jefferson / 1st Avenue,Phoenix,In Operation,-112.075202,33.447774,https://farm2.staticflickr.com/1542/2404118881...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,10013,70 South 1st Avenue,40131141001040,4013114100
84,84,88,36,Mesa Drive / Main Street,Mesa,In Operation,-111.822191,33.415078,https://farm6.staticflickr.com/5644/2404118669...,https://farm2.staticflickr.com/1716/2398921763...,...,NaN,NaN,NaN,NaN,NaN,NaN,18603,424 East Main Street,40134215011002,4013421501
85,85,89,22,50th St / Washington St,Phoenix,In Operation,-111.974741,33.446930,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,18716,4835 East Washingtpm Street,40131138011043,4013113801
86,86,90,37,Main St / Stapley Dr,Mesa,In Operation,-111.804935,33.415238,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,18717,1310 East Main Street,40134216012015,4013421601
87,87,91,38,Main St / Gilbert Rd,Mesa,In Operation,-111.789026,33.415376,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,18718,1864 East Main Street,40134216022000,4013421602

In [50]:
#make sure this table doesn't exist already in the DB
bus_df.to_sql('bus_data', engine, if_exists='replace')

In [51]:
# Create engine using the `FoodForAll.postgres` database file
engine = create_engine(f'postgresql://postgres:{pswrd}@localhost:{port}/{sql}')

In [52]:
#make sure this table doesn't exist already in the DB
lrail_df.to_sql('lrail_data', engine, if_exists='replace')

Creating Matplotlip charts - hopefully

In [ ]:
from matplotlib import pyplot as plt
from scipy import stats
import numpy as np
import pandas as pd